name: Weather Forecast

on:
  schedule:
    - cron: '0 */4 * * *' # Chạy mỗi 4 tiếng
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Weather
        # Sử dụng đúng Action của huantt
        uses: huantt/weather-forecast@master
        with:
          city: "Tra Vinh"
          days: 7
          weather-api-key: ${{ secrets.OPENWEATHERMAP_KEY }}
          # File mẫu để nó điền thời tiết vào (Xem bước 2)
          template-file: 'README.md.template'
          # File kết quả sẽ là README.md chính
          out-file: 'README.md'
